### ISSUE TITLE
Isn't working Properly

### ISSUE THREAD

**Issue by AdityaSoni19031997** [Krashcan/oreview#2]
![capture](https://cloud.githubusercontent.com/assets/22738086/22588849/a01dc9aa-ea2d-11e6-9fb7-0da2cd70a6f7.PNG)
It says that i have 127 videos but isn't displaying more than 10...
Even what it is displaying i doubt that i don't have any movie as criminal mind..
Worked correctly for 4 folders but didn't worked on the last one....
one last doubt.. it checks only for the folders not for the subfolders??

**Comment by Krashcan** [comment]
Are you sure the movies are named properly? Also, no. of videos = no. of files with mp4,3gp,mkv etc. extensions. If the application isn't able to determine a proper name for your movies inside the folder,it won't show them. If you can show a screenshot of the input and output, then that would be helpful.

**Comment by AdityaSoni19031997** [comment]
Ok I will send you

**Comment by AdityaSoni19031997** [comment]
Sorry for replying so late... Actually saw it just before few mins...

**Comment by AdityaSoni19031997** [comment]
![capture](https://cloud.githubusercontent.com/assets/22738086/25553615/9c3850b8-2cd5-11e7-9d79-985321a10a7d.PNG)
![capture1](https://cloud.githubusercontent.com/assets/22738086/25553616/9ce333b6-2cd5-11e7-97f2-9ca0dc5bc294.PNG)
![capture2](https://cloud.githubusercontent.com/assets/22738086/25553617/9f3505ea-2cd5-11e7-9bec-ca88f309ea9e.PNG)

I don't have this movie.........


![capture3](https://cloud.githubusercontent.com/assets/22738086/25553618/a0a9cc08-2cd5-11e7-82f4-561a4d549236.PNG)


I guess Interstellar , Avengers,  Jurassic Park ,  is also missing..
The videos count is perfect..
